import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Providers } from "./provider";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="flex flex-col h-screen"
      >
        <Providers>
          
            {/* <Header /> */}

          
          <div className="flex-grow">
            {children}

          </div>
          <Footer />

        </Providers>
      </body>
    </html>
  );
}
